package com.databricks.dicer.common

import scala.collection.immutable.SortedMap
import scala.collection.mutable
import scala.concurrent.Future

import com.databricks.caching.util.SequentialExecutionContext
import com.databricks.dicer.common.SlicezKeyTracker.SlicezKeyTrackable
import com.databricks.dicer.external.Target
import scalatags.Text.TypedTag
import scalatags.Text.all._

import com.databricks.dicer.common.ZPageHelpers.createCollapseButton
import com.databricks.dicer.external.{Slice, SliceKey}
import com.databricks.dicer.friend.Squid

import javax.annotation.concurrent.ThreadSafe

object CommonSlicez {

  /**
   * Background color displayed for the rows showing the assignment information in the
   * assignment information table.
   */
  private val ASSIGNMENT_BACKGROUND_COLOR = "PaleTurquoise"

  /**
   * Given an assignment, returns the generation of that assignment and the assignment in
   * human readable form. If the assignment is missing, returns two human-readable strings to
   * indicate so.
   */
  def getAssignmentString(
      assignmentOpt: Option[Assignment],
      reportedLoadPerResourceOpt: Option[Map[Squid, Double]],
      reportedLoadPerSliceOpt: Option[Map[Slice, Double]],
      topKeysOpt: Option[SortedMap[SliceKey, Double]],
      squidOpt: Option[Squid]): (String, String) = {
    assignmentOpt match {
      case Some(assignment: Assignment) =>
        val assignmentStringBuilder = mutable.StringBuilder.newBuilder
        AssignmentFormatter.appendAssignmentToStringBuilder(
          assignment,
          assignmentStringBuilder,
          maxResources = Int.MaxValue,
          maxSlices = Int.MaxValue,
          reportedLoadPerResourceOpt,
          loadPerSliceOverrideOpt = reportedLoadPerSliceOpt,
          topKeysOpt,
          squidFilterOpt = squidOpt
        )
        (
          assignment.generation.toString,
          assignmentStringBuilder.toString()
        )
      case None => ("None", "No assignment")
    }
  }

  /**
   * Given the generation string and the assignment string generated by [[getAssignmentString]],
   * returns the corresponding HTML page for it. This contains the generation string and a
   * collapsible element to make it possible to expand and hide the assignment.
   */
  def getAssignmentHtml(generationString: String, assignmentString: String): TypedTag[String] = {
    div(
      tr(
        backgroundColor := ASSIGNMENT_BACKGROUND_COLOR,
        th(colspan := 2, s"Generation: $generationString")
      ),
      tr(
        backgroundColor := ASSIGNMENT_BACKGROUND_COLOR,
        th(
          colspan := 2,
          div(
            createCollapseButton("Assignment"),
            div(`class` := "content", pre(assignmentString))
          )
        )
      )
    )
  }
}

/**
 *  A top-level trait representing different types of data used to render ZPages.
 *  See the case classes that extend this trait for specific kinds of SlicezData.
 */
trait SlicezData {

  /** Generates SlicezData content in HTML format. */
  def getHtml: TypedTag[String]
}

/**
 * An abstract class specifically designed for SlicezData that is associated with a single target.
 * Can be extended to implement additional functionality specific to either the assigner or the
 * client.
 *
 * @param target the target associated with this [[TargetSlicezData]].
 * @param sliceletsData the [[SliceletSubscriberSlicezData]] data for the Slicelets associated with
 *                      the target.
 * @param clerksData the [[ClerkSubscriberSlicezData]] data for the Clerks associated with the
 *                   target.
 * @param assignmentOpt the assignment currently associated with the target.
 * @param reportedLoadPerResourceOpt the reported load per resource associated with the assignment,
 *                                   if one exists.
 * @param reportedLoadPerSliceOpt the reported load per slice associated with the assignment,
 *                                if one exists.
 */
abstract class TargetSlicezData(
    target: Target,
    sliceletsData: Seq[SliceletSubscriberSlicezData],
    clerksData: Seq[ClerkSubscriberSlicezData],
    assignmentOpt: Option[Assignment])
    extends SlicezKeyTrackable {

  import TargetSlicezData.{
    TARGET_NAME_BACKGROUND_COLOR,
    SLICELET_TABLE_BACKGOUND_COLOR,
    CLERK_TABLE_BACKGROUND_COLOR,
    EMPTY_HTML
  }

  /** Returns the target associated with this [[TargetSlicezData]]. */
  final def getTarget: Target = {
    target
  }

  /** Returns the assignment associated with this [[TargetSlicezData]]. */
  final def getAssignmentOpt: Option[Assignment] = {
    assignmentOpt
  }

  /**
   * Create an HTML div containing subscribers information associated with this
   * [[TargetSlicezData]]. The div structure with example data is as follows:
   * {{{
   *   | Target: softstore-storelet, Slicelets: 2, Clerks: 1              |
   *   | Slicelet Debug Name                    | Slicelet Address        |
   *   | S0-softstore-storelet-localhost:63751  | https://localhost:63751 |
   *   | S0-softstore-storelet-localhost:63752  | https://localhost:63752 |
   *   | Clerk Debug Name                                                 |
   *   | C0-dicer-clerk-localhost:63753                                   |
   *  }}}
   */
  final def createSubscriberDiv: TypedTag[String] = {
    div(
      // Append the target overview row.
      tr(
        backgroundColor := TARGET_NAME_BACKGROUND_COLOR,
        th(
          colspan := 2,
          s"Target: ",
          strong(target.toParseableDescription),
          s" Slicelets: ${sliceletsData.size}",
          s" Clerks: ${clerksData.size}"
        )
      ),
      // Append the slicelets data header if there is one or more Slicetlets.
      if (sliceletsData.nonEmpty) {
        tr(
          backgroundColor := SLICELET_TABLE_BACKGOUND_COLOR,
          td("Slicelet Debug Name"),
          td("Slicelet Address")
        )
      } else {
        // Scalatags requires to have an else-branch for every if-branch.
        // So we append EMPTY_HTML in the else branch.
        EMPTY_HTML
      },
      // Append individual Slicelet data.
      for (sliceletData <- sliceletsData)
        yield createSliceletsRow(sliceletData),
      // Append the clerks data header there is one or more Clerks.
      if (clerksData.nonEmpty) {
        tr(
          backgroundColor := CLERK_TABLE_BACKGROUND_COLOR,
          th(colspan := 2, "Clerk Debug Name")
        )
      } else {
        EMPTY_HTML
      },
      // Append individual Clerk data.
      for (clerkData <- clerksData)
        yield createClerkRow(clerkData)
    )
  }

  /**
   * Create an HTML div containing assignment information associated with this
   * [[TargetSlicezData]]. The div structure with example data is as follows:
   * {{{
   *   | Target: targetName                                               |
   *   | Generation: None / Assignment Info                               |
   *   | + Assignment (a collapsible element for assignment information)  |
   * }}}
   *
   * Implemented by the derived classes, where the assignment information displayed
   * may vary slightly based on additional information in the derived classes. See
   * the implementations in the derived classes for more details.
   */
  def createAssignmentDiv: TypedTag[String]

  /**
   * Searches for and returns the String representation of the [[SliceAssignment]]
   * associated with a SliceKey in this SlicezData. Returns `None` only when `getAssignmentOpt` is
   * empty.
   */
  override final def searchBySliceKey(sliceKey: SliceKey): Option[String] = {
    val sliceAssignmentOpt: Option[SliceAssignment] = getAssignmentOpt.map {
      (_: Assignment).sliceMap.lookUp(sliceKey)
    }
    sliceAssignmentOpt.map { (_: SliceAssignment).toString }
  }

  /** Returns the Html table content for a single Slicelet. */
  private def createSliceletsRow(data: SliceletSubscriberSlicezData): TypedTag[String] = {
    tr(
      backgroundColor := SLICELET_TABLE_BACKGOUND_COLOR,
      td(data.debugName),
      td(data.address)
    )
  }

  /** Returns the HTML table content for a single Clerk. */
  private def createClerkRow(clerkSlicezData: ClerkSubscriberSlicezData): TypedTag[String] = {
    tr(
      backgroundColor := CLERK_TABLE_BACKGROUND_COLOR,
      th(
        colspan := 2,
        clerkSlicezData.debugName
      )
    )
  }
}

/** A set of constants for TargetSlicezData to use. */
object TargetSlicezData {

  /**
   * Background color displayed for the rows showing the target name in all tables.
   */
  private val TARGET_NAME_BACKGROUND_COLOR = "PaleGreen"

  /**
   * Background color displayed for the rows showing the Slicelet data in the subscriber
   * information table.
   */
  private val SLICELET_TABLE_BACKGOUND_COLOR = "Moccasin"

  /**
   * Background color displayed for the rows showing the Clerk data in the subscriber
   * information table.
   */
  private val CLERK_TABLE_BACKGROUND_COLOR = "Pink"

  /** An empty HTML content. */
  private val EMPTY_HTML = ""
}

/** Class that tracks the Slicez-relevant data for a Slicelet (its debug name and address). */
case class SliceletSubscriberSlicezData(debugName: String, address: String)

/** A class to track the Slicez-relevant data for a Clerk. */
case class ClerkSubscriberSlicezData(debugName: String)

/**
 * This class manages the tracking of assignments for specific target-key pairs subscribed by users
 * on the debug page.
 * The assignment information (if exists) of the subscribed target-key pairs will be shown on the
 * debug Zpage.
 *
 * @param sec the sequential execution context on which to run `slicezKeyTracker`. It protects the
 *            state of `slicezKeyTracker`.
 */
@ThreadSafe
class SlicezAssignmentKeyTracker(sec: SequentialExecutionContext) {

  /** The general instructions on how to use the tracker. */
  private val TRACKER_ASSIGNMENT_INSTRUCTION_HEADER =
    """Track the assignment of the keys!"""
  private val TRACKER_ASSIGNMENT_INSTRUCTION_USAGE =
    """Type in the key you want to keep/remove track of in the target's
      |corresponding input box, and click submit!""".stripMargin
  private val TRACKER_ASSIGNMENT_INSTRUCTION_NOTE =
    """These actions will not affect the assignments produced by Dicer, but will only change the
      |contents of this page.""".stripMargin

  /**
   * The generic key tracker that keeps tracks of the subscribed target-key pairs, and generates the
   * corresponding HTML component for the tracker.
   */
  private val slicezKeyTracker = new SlicezKeyTracker("Assignment", sec)

  /** Returns a Future of assignment tracker HTML based on the sequence of [[TargetSlicezData]]. */
  def getHtml(targetSlicezDataSeq: Seq[TargetSlicezData]): Future[TypedTag[String]] = {
    val assignmentTrackerPrompt: TypedTag[String] =
      div(
        br(),
        strong(TRACKER_ASSIGNMENT_INSTRUCTION_HEADER),
        br(),
        "This key tracker searches keys in the full assignment and returns slice assignments ",
        "where the primaryRateLoad",
        br(),
        "is recorded by the time the generation is created. So the load information might be ",
        strong("STALE"),
        ".",
        br(),
        TRACKER_ASSIGNMENT_INSTRUCTION_USAGE,
        br(),
        TRACKER_ASSIGNMENT_INSTRUCTION_NOTE
      )
    slicezKeyTracker
      .getHtml(targetSlicezDataSeq)
      .map((trackerHtml: TypedTag[String]) => {
        div(
          assignmentTrackerPrompt,
          trackerHtml
        )
      })(sec)
  }
}
